openapi: 3.0.0
info:
  title: Person API
  description: A simple API for CRUD operations on Person entity.
  version: 1.0.0
paths:
  /persons:
    get:
      summary: Get all persons
      responses:
        '200':
          description: OK
    post:
      summary: Add a person
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        '201':
          description: Created
  /persons/{person_id}:
    get:
      summary: Get a person by ID
      parameters:
        - in: path
          name: person_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
    patch:
      summary: Update a person
      parameters:
        - in: path
          name: person_id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete a person
      parameters:
        - in: path
          name: person_id
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: No Content
